SET PAGESIZE 80
SET LINESIZE 200
SET FEEDBACK OFF
SET COLSEP ' | '
PROMPT ==== 该患者 MEDICAL_RECORDS 全部记录 ====
SELECT RECORD_ID, RECORD_TYPE, RECORDING_DOCTOR, TO_CHAR(RECORD_TIME,'YYYY-MM-DD HH24:MI') AS REC_TIME, SUBSTR(MEDICAL_CONTENT,1,60) AS CONTENT_PREVIEW
FROM MEDICAL_RECORDS
WHERE PATIENT_ID='99050801359098_1' AND IS_DELETED=0
ORDER BY RECORD_TIME;
PROMPT ==== MEDICAL_RECORDS 全局记录类型分布 ====
SELECT RECORD_TYPE, COUNT(*) AS CNT FROM MEDICAL_RECORDS WHERE IS_DELETED=0 GROUP BY RECORD_TYPE ORDER BY CNT DESC;
EXIT;
